### ISSUE TITLE
2.5.0 release incompatibilities

### ISSUE THREAD

**Issue by stevend** [envato/jwt_signed_request#36]
In the recent release of version 2.5.0 ( See #35 ), a recommended change was made to the format of the `Authorization` request header. This header gets set by the provided Faraday middleware (if using it).

Subsequently a change was made to the `Verify` class to support extracting the jwt token from both the old and new format of the `Authorization` request header.

I have however ran into an undocumented compatibility issue when a request verifying service running version `< 2.5.0` receives a signed request (signed using the faraday middleware) from a service running `>= 2.5.0`. The issue is that the verifying service on the older version does not know how to handle the changed format of the Authorization request header and fails to extract the jwt token correctly. This causes all requests to fail authorization, even with a valid set of keys.

For context here is how the `Authorization` request header is constructed
Before (< 2.5.0): `<jwt_token>` 
After (>= 2.5.0):   `Bearer <jwt_token>`

When it comes to verification...
Before (< 2.5.0): Value of the `Authorization` request header is assumed to be the jwt_token 
After (>= 2.5.0): jwt token is extracted via the second matched element of this regex (`/\A(Bearer\s+)?([^*]+)\z/`) which happily supports the existence or non existence of `Bearer ` 👍 

To summarise, here is a table of version scenarios that illustrates what will and will not work

| Signing service | Verifying service | Verification result |
|:-----------------:|:-----------------:|:-------------------:|
| 2.4.1 | 2.4.1 | 👍|
| 2.4.1 | 2.5.0 | 👍|
| 2.5.0 | 2.5.0 | 👍|
| 2.5.0 | 2.4.1 | 👎 |

I happened to discover this issue whilst working with some services in development. However it also popped up briefly in a production environment when one system signing requests did a `bundle update` and the services it was sending requests to were not yet updated and failing requests.

I don't think (?) there is a way to make this change fully backwards compatible, however I think we can do better to highlight this scenario and save the users of this gem some headaches and potentially a lot of wasted time figuring out an otherwise obscure problem.

I'm wondering in this case, other than updating the changelog to highlight this potential system integration change. Would we still deem it correct to be a minor version upgrade? I'm inclined to say yes as in isolation the code does support request headers in both formats.

What do others think? (and pro tip don't upgrade your signing services until the verification service has been updated)

**Comment by yoshdog** [comment]
Do u know which systems it impacted in production @stevend ?

I think for now we can update the changelog with the compatibility table you used would be a good first step.

**Comment by yoshdog** [comment]
btw thanks for @stevend for the writeup and investigation. Sorry that v2.5.0 wasted some of your time.

**Comment by patrobinson** [comment]
@stevend with my hindsight goggles firmly fitted, a better way to handle this change would've been to release 2.5.0 to be backwards compatible, by adding the optional `Bearer` regex to the Verify class. Then release 3.0 which makes the breaking change which inserts that keyword into the header, along with release notes to state all upstream systems must be running 2.5.0 or above. 

But I have no skin in the game, so I'm not sure what the best path forward is now that this breaking change has been made.

**Comment by stevend** [comment]
@yoshdog no problem, I just hope to help others not run into the issue. I'll PM you regarding specific systems

**Comment by stevend** [comment]
I think the way forward is to 
* Update the changelog to identify the potential issue upgrading to 2.5.0
* Revert the change of assigning the Bearer prefix in the faraday middleware (as a patch version)

Allow teams to freely update their version without system dependency impact

* Re-instate the Bearer prefix in a later version and state the breaking change and version requirements of any verifying/downstream systems (not really an urgent change)

**Comment by zubin** [comment]
How about releasing v2.5.1 which adds a `bearer_syntax: false` kwarg to `.sign`? (or perhaps this can be set in config). Defaulting to false will resolve the incompatibility issue, and the default can become `true` in v3.

**Comment by jacobbednarz** [comment]
Nice find @stevend! In the past, to avoid shipping a backwards incompatible change we've used hints from the client (such as the version or fingerprint sent in the payload) to determine which code path should be executed. I.e. here, we could have checked for the version in use (on the client and server) and negotiated whether to include the scheme based on the lowest version in use.

Based on my understanding here, this issue would be isolated to only services that are running this gem *and* the version less than 2.5.x, correct? Prior to the change in #35, this library wasn't actually abiding by the specifications and if it tried to communicate with any of the other supported JWT implementations, would have failed the authorisation dance.

I wasn't involved in the versioning decisions here but I'm with you on the versioning that in isolation, the change was in fact backwards compatible and doesn't break the semantic versioning contract. The issue only appears when you're running the same gem but with two different versions which I suspect isn't something that should work flawlessly.

In terms of next steps, I'd suggest we update the documentation at a minimum to point out the edge case where there is a differing versioning with the recommendation of always running all the parties involved on the same version. I don't think a hard and fast rule of always update the verifying service first would be adequate as there are other parts of the code that could be considered a backwards compatible change that would trigger the scenario you hit here but in reverse.

**Comment by stevend** [comment]
I'll get a PR up and see what we can figure out, thanks for the suggestions
